apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp

  template:
    metadata:
      # Labels dan annotations untuk pod di tempatkan disini
      labels:
        app: my-webapp
        tier: frontend
      annotations:
        # Anotasi untuk manusia (informasi)
        owner: "Tim web Frontend"
        contact-email: "frontend@example.com"
        description: "Pod ini menjalankan nginx sebagai web server utama aplikasi"
        # Anotasi yang mungkin digunakan oleh tools
        git-commit-hash: "f2sssss"
        promotheus.io/scrape: "true"
        promotheus.io/port: "9113"
    
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21
        ports:
        - containerPort: 80