apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  # Labels dan annotations untuk pod di tempatkan disini
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value
    annotation-key2: bla bla bla, veri long annotation value
spec:
  containers:
    - name: container-annotation
      image: nginx
      ports:
        - containerPort: 80