apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      web: nginx
  template:
    metadata:
      name: nginx
      labels:
        web: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    web: nginx
  ports:
      # Port Internal Cluster
    - port: 80
      # Port yang ada didalam container contoh Nginx
      targetPort: 80
      # Port External di setiap Node
      # Rentang NodePort 30000-32767
      nodePort: 30001
