apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nodejs-web 
  labels: 
    app: nodejs 
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: nodejs 
  template: 
    metadata: 
      name: nodejs-web  
      labels: 
        app: nodejs 
    spec: 
      containers: 
        - name: nodejs-web 
          image: mochabdulrouf/nodejs-focustimer-app
          ports:
            - containerPort: 2122
          resources:
            requests: 
              # cpu = 500m berarti setengah (0,5) core cpu
              cpu: 500m 
              # memory = 1000Mi berarti sekitar 1048 MegaByte (MB) sedikit dibawah 1 GigaByte (GB)
              memory: 1000Mi
            limits: 
              cpu: 500m  
              memory: 1000Mi 
          
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: nodejs-service 
spec: 
  type: NodePort 
  selector: 
    app: nodejs 
  ports:
    - port: 2022 
      targetPort: 2122
      nodePort: 30002