apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: nodejs-writer-volume
spec:
  accessModes:
    # Volume ini hanya bisa di pasang (mounts) sebagai read write oleh satu node pada satu waktu
    - ReadWriteOnce 
  capacity:
    # Kapasitas penyimpanan untuk volume ini 5 Gigabyte
    storage: 5Gi
  # HostPath berarti penyimpanan ada disebuah direktori pada node
  hostPath:
    path: /data/location 
# note: PV menyediakan penyimpanan sebesar 5 Gigabyte di direktori /data/location pada node cluster


---

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: nodejs-writer-claim 
spec: 
  # Mode akses PVC ini harus cocok dengan mode akses PV yang akan di klaim
  accessModes:
    - ReadWriteOnce
  # Menentukan menggunakan volume dalam bentuk filesystem
  volumeMode: Filesystem 
  # Menentukan sumber daya yang diminta oleh PVC
  resources:
    requests:
      # Meminta penyimapan sebesar 1 Gigabyte
      storage: 1Gi
# note: PVC meminta penyimpanan sebesar 1 Gigabyte dengan mode akses ReadWriteOnce

---

apiVersion: v1 
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    app: nodejs
spec:
  # Membuat volume dengan nama html disini
  volumes:
    - name: html
      # Memberitahu kubernetes bahwa sumber volume ini berasal dari klaim PVC dengan nama nodejs-writer-claim.
      persistentVolumeClaim:
        claimName: nodejs-writer-claim
  containers:
    - name: nodejs-writer
      image: mochabdulrouf/nodejs-writer-v3
      volumeMounts:
        # Memasang (mount) volume bernama html ke dalam container pada path /app/html
        - mountPath: /app/html
          name: html
