# NodeJS ConfigMap With Volume

apiVersion: v1 
kind: Secret
metadata:
  name: nodejs-secret
stringData: 
    APP_VERSION: "2.1.2"
    NODE_ENV: "Production"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      # Memberikan nama volume app-config-volume
      containers:
        - name: nodejs-env
          image: mochabdulrouf/nodejs-app-env
          # Tetap memasukan ConfigMap ke dalam Container 
          # Supaya key Value tetap menjadi Environment Variable di dalam Container
          envFrom:
            - secretRef:
                name: nodejs-secret


---

apiVersion: v1 
kind: Service
metadata:
  name: nodejs-env-serv
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 2122
      targetPort: 2122
      nodePort: 30003