apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-configmap
data:
  # Membuat key value berdasarkan environment variable di aplikasi NodeJS
  APP_VERSION: "2.1.2"
  NODE_ENV: "Staging"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-env
          image: mochabdulrouf/nodejs-app-env
          # Memasukan ConfigMap ke dalam Container sebagai Environment Variable
          envFrom:
            - configMapRef:
                name: nodejs-configmap

---

apiVersion: v1 
kind: Service
metadata:
  name: nodejs-env-serv
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 2122
      targetPort: 2122
      nodePort: 30002
      
