apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-nodejs
  labels:
    name: cronjob-nodejs 
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cronjob-nodejs
          labels:
            name: cronjob-nodejs
        spec:
          restartPolicy: Never
          containers: 
            - name: cronjob-nodejs
              image: khannedy/nodejs-job