apiVersion: v1 
kind: Pod
metadata:
  name: nodejs-app
  labels:
    app: nodejs-writer
spec:
  volumes:  
    - name: html
      emptyDir: {}
  containers:
    - name: nodejs-writer 
      image: mochabdulrouf/nodejs-writer-v3
      volumeMounts:
        - mountPath: /app/app-environment
          name: html
      env:
        # NodeJS akan menulis file ke direktori /app/app-environment 
        - name: HTML_LOCATION
          value: /app/app-environment