apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nodejs-web 
  labels: 
    app: nodejs 
spec: 
  selector: 
    matchLabels:
      app: nodejs 
  template: 
    metadata: 
      name: nodejs-web 
      labels: 
        app: nodejs 
    spec: 
      containers: 
        - name: nodejs-cn 
          image: mochabdulrouf/nodejs-focustimer-app:2.0 
          ports: 
            - containerPort: 2122

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: service-nodejs 
spec: 
  type: NodePort 
  selector: 
    app: nodejs 
  ports: 
    - port: 2122
      targetPort: 2122 
      nodePort: 30002

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: hpa-nodejs 
spec: 
  minReplicas: 3 
  maxReplicas: 5 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: nodejs-web
  # Mendefinisikan aturan metric yang akan digunakan oleh HPA untuk memutuskan
  # kapan menambah dan mengurangi jumlah Pod
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          # rata rata penggunaan
          type: Utilization
          averageUtilization: 70 
    - type: Resource
      resource: 
        name: memory 
        target: 
          type: Utilization 
          averageUtilization: 70