apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-configmap
data:
  # Membuat key value berdasarkan environment variable di aplikasi NodeJS
  APP_VERSION: "2.1.2"
  NODE_ENV: "Staging"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-env
          image: mochabdulrouf/nodejs-app-env
          
          # Blok ini menambahkan resource khusus untuk container
          resources:
            requests:
              cpu: "500m" # Meminta 0.5 CPU
              memory: "128Mi" # Meminta 128MiB memory
          
          # Memasukan ConfigMap ke dalam Container sebagai Environment Variable
          envFrom:
            - configMapRef:
                name: nodejs-configmap
          # Mendefinisikan Environment Variable dari Downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            # Memberikan informarsi resource request ke dalam Container
            - name: REQUEST_CPU
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
                  
  # Note: nilai dari cpu akan di bulatkan menjadi 1 bukan 0,5 didalam environment variable


---

apiVersion: v1 
kind: Service
metadata:
  name: nodejs-env-serv
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 2122
      targetPort: 2122
      nodePort: 30002
      
